In [14]:
import numpy as np
import pandas as pd

In [15]:
raw_data_file = '../data/raw_data/all_data.xlsx'

In [16]:
raw_data = pd.read_excel(open(raw_data_file, 'rb'), sheet_name = 0)

In [17]:
raw_data

,office,weather,Setup,Occupant ID,"Cluster (1: bright, 2: moderate, 3: dark)","Combination (1: zero distance, 2: medium distance, 3: maximum distance)",arrival,work plane setpoint,light setpoint,ddd,...,Hor after,What is your gender?,How old are you?,shade setpoint,AirTemp_left,AirTemp_right,STPT,VerIll,Pyranometer,WindowIll
0,1022,partly sunny,2,1,3,1,1,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1022,partly sunny,2,1,3,2,0,700,25.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1022,partly sunny,2,1,3,3,0,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1022,partly sunny,2,1,3,1,1,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1022,partly sunny,2,1,3,3,0,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1022,partly sunny,2,1,3,2,0,800,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1022,completely cloudy,2,7,3,2,1,700,25.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1022,completely cloudy,2,7,3,1,0,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1022,completely cloudy,2,7,3,3,0,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1022,completely cloudy,2,7,3,1,1,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1022,completely cloudy,2,7,3,2,0,700,25.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1022,completely cloudy,2,7,3,3,0,2000,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1022,cloudy,2,9,3,2,1,700,25.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1022,cloudy,2,9,3,1,0,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1022,cloudy,2,9,3,3,0,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1022,cloudy,2,9,3,1,1,300,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1022,cloudy,2,9,3,2,0,700,25.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1022,cloudy,2,9,3,3,0,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1022,partly sunny,2,1,3,1,1,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1022,partly sunny,2,1,3,2,0,700,25.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1022,partly sunny,2,1,3,3,0,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1022,partly sunny,2,1,3,1,1,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1022,partly sunny,2,1,3,3,0,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1022,partly sunny,2,1,3,2,0,800,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1022,sunny,2,1,3,3,1,1500,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1022,sunny,2,1,3,2,0,800,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1022,sunny,2,1,3,1,0,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1022,sunny,2,1,3,2,1,800,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1022,sunny,2,1,3,3,0,1500,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1022,sunny,2,1,3,1,0,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,1022,Cloudy,2,17,3,2,1,700,25.0,0,...,285.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
385,1022,Cloudy,2,17,3,1,0,300,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
386,1022,Cloudy,2,17,3,3,0,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387,1022,Cloudy,2,17,3,1,1,300,100.0,1,...,1203.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,1022,Cloudy,2,17,3,3,0,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
389,1022,Cloudy,2,17,3,2,0,700,25.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
390,1034,Cloudy,2,17,3,1,1,300,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
391,1034,Cloudy,2,17,3,3,0,2000,100.0,0,...,658.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
392,1034,Cloudy,2,17,3,2,0,700,25.0,0,...,337.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
393,1034,Cloudy,2,17,3,3,1,2000,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,1034,Cloudy,2,17,3,1,0,300,100.0,0,...,956.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,1034,Cloudy,2,17,3,2,0,700,25.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,1022,Cloudy,2,18,1,3,1,300,0.0,0,...,1895.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,1022,Cloudy,2,18,1,1,0,1100,100.0,0,...,504.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,1022,Cloudy,2,18,1,2,0,500,25.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,1022,Cloudy,2,18,1,1,1,1100,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400,1022,Cloudy,2,18,1,2,0,500,25.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401,1022,Cloudy,2,18,1,3,0,300,0.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402,1022,Sunny,1,17,3,1,1,300,0.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
403,1022,Sunny,1,17,3,3,0,1500,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
404,1022,Sunny,1,17,3,2,0,800,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,1022,Sunny,1,17,3,3,1,1500,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
406,1022,Sunny,1,17,3,2,0,800,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407,1022,Sunny,1,17,3,1,0,300,0.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,1034,Sunny,1,19,1,2,1,700,50.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,1034,Sunny,1,19,1,1,0,1100,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,1034,Sunny,1,19,1,3,0,300,0.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,1034,Sunny,1,19,1,1,1,1100,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
412,1034,Sunny,1,19,1,2,0,700,50.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
413,1034,Sunny,1,19,1,3,0,300,0.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
raw_data.columns

Index([u'office', u'weather', u'Setup', u'Occupant ID',
       u'Cluster (1: bright, 2: moderate, 3: dark)',
       u'Combination (1: zero distance, 2: medium distance, 3: maximum distance)',
       u'arrival', u'work plane setpoint', u'light setpoint', u'ddd',
       u'interface-brighter', u'interface-darker', u'interface-glare',
       u'interface-privacy', u'interface-view', u'interace- sahde warmer',
       u'Interface-shade cooler', u'Start Date', u'End Date',
       u'How would you describe the current lighting condition at your workspace? (1: very dark … 7: very bright)',
       u'How satisfied are you with the current lighting condition? (1: brighter, 2: darker, 3: satisfied)',
       u'How would you rate your current work productivity?',
       u'What type of office work have you been doing since the last time you completed the survey?',
       u'In general, what is your preference for lighting condition at your workspace?',
       u'In general how sensitive to brightness do you consider yourself?',
       u'In general, how important is it for you to have a clear view to outside while working at your workspace?',
       u'Shade', u'LightLevel', u'HorIll', u'shade after', u'light after',
       u'Hor after', u'What is your gender?', u'How old are you?',
       u'shade setpoint', u'AirTemp_left', u'AirTemp_right', u'STPT',
       u'VerIll', u'Pyranometer', u'WindowIll'],
      dtype='object')

In [6]:
bool1 = raw_data['interface-brighter'] == 1
bool2 = raw_data['interface-darker'] == 1
bool3 = raw_data['interface-glare'] == 1
bool4 = raw_data['interface-privacy'] == 1
bool5 =  raw_data['interace- sahde warmer'] == 1
bool6 =  raw_data['Interface-shade cooler'] == 1
bool7 =  raw_data['interface-view'] == 1

bool_all = np.any([bool1, bool2, bool3, bool4, bool5, bool6, bool7], axis = 0)
all_actions_data = raw_data[bool_all]

In [7]:
all_actions_data

,office,weather,Setup,Occupant ID,"Cluster (1: bright, 2: moderate, 3: dark)","Combination (1: zero distance, 2: medium distance, 3: maximum distance)",arrival,work plane setpoint,light setpoint,ddd,...,Hor after,What is your gender?,How old are you?,shade setpoint,AirTemp_left,AirTemp_right,STPT,VerIll,Pyranometer,WindowIll
6,1022,completely cloudy,2,7,3,2,1,700,25.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1022,completely cloudy,2,7,3,3,0,2000,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1022,cloudy,2,9,3,1,1,300,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1022,sunny,2,1,3,3,0,1500,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1022,sunny,2,9,3,3,1,1500,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1022,sunny,2,9,3,2,1,800,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,1022,sunny,2,9,3,3,0,1500,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,1022,sunny,2,9,3,2,1,800,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,1022,sunny,2,9,3,3,0,1500,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,1022,sunny,2,9,3,3,1,1500,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,1020,sunny,2,2,3,3,1,300,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,1020,sunny,2,2,3,2,1,800,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,1020,partly sunny,2,2,3,2,1,800,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,1020,partly sunny,2,2,3,3,0,1500,100.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,1020,partly sunny,2,2,3,2,0,800,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,1020,sunny,2,3,2,3,1,750,40.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,1022,sunny,2,4,2,3,1,1800,75.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,1020,cloudy,2,6,2,3,1,1700,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,1020,cloudy,2,6,2,2,1,1100,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,1020,cloudy,2,6,2,3,0,200,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,1020,cloudy,2,4,2,3,1,200,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,1020,cloudy,2,4,2,3,1,200,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,1022,partly sunny,2,3,2,3,1,200,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,1020,sunny,2,11,1,2,1,700,50.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1034,sunny,2,14,1,3,1,300,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,1034,sunny,2,14,1,2,0,700,50.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,1034,sunny,2,14,1,3,1,300,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,1034,sunny,2,14,1,2,0,700,50.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,1020,sunny,2,14,1,2,1,700,50.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,1020,sunny,2,14,1,3,0,300,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,1022,partly cloudy,2,10,3,3,0,2000,100.0,0,...,876.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,1022,partly cloudy,2,10,3,3,1,2000,100.0,0,...,548.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,1022,cloudy,2,10,3,3,1,2000,100.0,0,...,630.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,1022,cloudy,2,10,3,3,0,2000,100.0,0,...,1194.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,1034,partly cloudy,2,16,1,1,1,1100,100.0,1,...,3118.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,1034,partly cloudy,2,16,1,3,0,300,NaN,0,...,424.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,1034,partly cloudy,2,16,1,2,0,500,25.0,0,...,1230.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,1034,partly cloudy,2,16,1,3,1,300,NaN,0,...,928.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,1034,partly cloudy,2,16,1,2,0,500,25.0,0,...,2116.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,1034,cloudy,2,16,1,3,1,300,NaN,0,...,3332.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,1034,cloudy,2,16,1,2,0,500,25.0,0,...,1979.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327,1034,cloudy,2,16,1,2,1,500,25.0,0,...,1540.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,1034,cloudy,2,16,1,3,0,300,NaN,0,...,1698.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,1020,Sunny,2,12,1,1,0,1100,100.0,1,...,1908.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,1034,Sunny,2,13,1,1,0,1100,100.0,1,...,2879.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,1034,Sunny,2,13,1,2,0,700,50.0,1,...,1563.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,1022,Sunny,2,10,3,1,0,300,0.0,1,...,890.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,1020,Sunny,2,12,1,1,0,1100,100.0,1,...,1763.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,1034,Sunny,2,13,1,1,0,1100,100.0,1,...,2437.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,1020,Sunny,2,17,3,1,0,300,100.0,0,...,1123.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,1020,Sunny,2,17,3,2,0,800,100.0,0,...,398.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,1022,Sunny,2,16,1,3,1,300,0.0,0,...,2895.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,1034,Sunny,2,13,1,2,0,700,50.0,1,...,1654.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
384,1022,Cloudy,2,17,3,2,1,700,25.0,0,...,285.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387,1022,Cloudy,2,17,3,1,1,300,100.0,1,...,1203.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
391,1034,Cloudy,2,17,3,3,0,2000,100.0,0,...,658.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
392,1034,Cloudy,2,17,3,2,0,700,25.0,0,...,337.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,1034,Cloudy,2,17,3,1,0,300,100.0,0,...,956.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,1022,Cloudy,2,18,1,3,1,300,0.0,0,...,1895.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,1022,Cloudy,2,18,1,1,0,1100,100.0,0,...,504.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
all_actions_data.to_csv('../data/raw_data/all_action_data.csv', encoding='utf-8', index=False)

In [32]:
print bool1.sum()
print bool2.sum()
print bool3.sum()
print bool4.sum()
print bool5.sum()
print bool6.sum()
print bool7.sum()

29
39
0
23
0
0
32

In [23]:
#a = raw_data[raw_data['Setup'] == 2]

In [24]:
#a.to_csv('../data/raw_data/a.csv', encoding='utf-8', index=False)

In [19]:
bool_act = raw_data.ddd == 0

In [21]:
bool_act.sum()

73