In [1]:
import sys
sys.path.append('../')
from GPPrefAct import data_gen

/Users/nimishawalgaonkar/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
raw_data_file = '../data/raw_data/DATA.xlsx'
DObj = data_gen.DataGen(raw_data_file)

In [3]:
DObj.previous_column_names

Index([u'office', u'weather', u'Setup', u'Occupant ID',
       u'Cluster (1: bright, 2: moderate, 3: dark)',
       u'Combination (1: zero distance, 2: medium distance, 3: maximum distance)',
       u'arrival', u'work plane setpoint', u'light setpoint', u'ddd',
       u'interface-brighter', u'interface-darker', u'interface-glare',
       u'interface-privacy', u'interface-view', u'interace- sahde warmer',
       u'Interface-shade cooler', u'Start Date', u'End Date',
       u'How would you describe the current lighting condition at your workspace? (1: very dark â€¦ 7: very bright)',
       u'How satisfied are you with the current lighting condition? (1: brighter, 2: darker, 3: satisfied)',
       u'How would you rate your current work productivity?',
       u'What type of office work have you been doing since the last time you completed the survey?',
       u'In general, what is your preference for lighting condition at your workspace?',
       u'In general how sensitive to brightness do you consider yourself?',
       u'In general, how important is it for you to have a clear view to outside while working at your workspace?'],
      dtype='object')

In [4]:
DObj.concerned_data.keys()

Index([u'Office_ID', u'Weather', u'Setup', u'Occupant_ID', u'Cluster',
       u'Distance', u'Arrival_I', u'WI', u'LI', u'ddd', u'I_B', u'I_D', u'I_G',
       u'I_P', u'I_V', u'I_SW', u'I_SC', u'SD', u'ED', u'LCAW', u'SQuery',
       u'CWP', u'TW', u'G_P', u'G_S', u'G_V'],
      dtype='object')

In [5]:
Setup1, Setup2 = DObj.get_all_individual_occ_setup()

In [6]:
Setup1

[     Office_ID Weather  Setup  Occupant_ID  Cluster  Distance  Arrival_I  \
 158       1034   sunny      1            1        3         1          1
 159       1034   sunny      1            1        3         2          0
 160       1034   sunny      1            1        3         3          0
 161       1034   sunny      1            1        3         1          1
 162       1034   sunny      1            1        3         3          0
 163       1034   sunny      1            1        3         2          0

        WI     LI  ddd ...   I_SC                  SD                  ED  \
 158   300    NaN    1 ...      0 2018-01-18 10:52:59 2018-01-18 10:53:11
 159   700   25.0    1 ...      0 2018-01-18 11:14:29 2018-01-18 11:14:40
 160  2000  100.0    1 ...      0 2018-01-18 11:42:57 2018-01-18 11:43:10
 161   300    NaN    1 ...      0 2018-01-18 12:17:00 2018-01-18 12:17:24
 162  2000  100.0    1 ...      0 2018-01-18 13:17:50 2018-01-18 13:18:03
 163   700   25.0    1 ...      0 2018-01-18 13:43:30 2018-01-18 13:43:44

      LCAW  SQuery  CWP   TW G_P G_S  G_V
 158   4.0     3.0  3.0  1.0   2   5    1
 159   5.0     3.0  3.0  1.0   2   5    1
 160   6.0     2.0  2.0  1.0   2   5    1
 161   3.0     3.0  3.0  1.0   2   5    1
 162   7.0     2.0  1.0  3.0   2   5    1
 163   5.0     2.0  3.0  1.0   2   5    1

 [6 rows x 26 columns],
      Office_ID       Weather  Setup  Occupant_ID  Cluster  Distance  \
 114       1034  partly sunny      1            2        3         1
 115       1034  partly sunny      1            2        3         2
 116       1034  partly sunny      1            2        3         3
 117       1034  partly sunny      1            2        3         1
 118       1034  partly sunny      1            2        3         3
 119       1034  partly sunny      1            2        3         2

      Arrival_I    WI     LI  ddd ...   I_SC                  SD  \
 114          1   300    NaN    0 ...      0                 NaT
 115          0   700   25.0    1 ...      0 2017-12-07 11:24:09
 116          0  2000  100.0    1 ...      0 2017-12-07 11:50:21
 117          1   300    NaN    1 ...      0 2017-12-07 12:43:12
 118          0  2000  100.0    1 ...      0 2017-12-07 13:57:43
 119          0   700   25.0    1 ...      0 2017-12-07 14:30:42

                      ED  LCAW  SQuery  CWP   TW G_P G_S  G_V
 114                 NaT   NaN     NaN  NaN  NaN   3   4    2
 115 2017-12-07 11:24:23   5.0     2.0  3.0  1.0   3   4    2
 116 2017-12-07 11:50:32   6.0     2.0  2.0  1.0   3   4    2
 117 2017-12-07 12:43:21   3.0     3.0  5.0  1.0   3   4    2
 118 2017-12-07 13:58:58   6.0     2.0  2.0  1.0   3   4    2
 119 2017-12-07 14:30:54   5.0     2.0  3.0  3.0   3   4    2

 [6 rows x 26 columns],
      Office_ID       Weather  Setup  Occupant_ID  Cluster  Distance  \
 210       1022  partly sunny      1            3        2         3
 211       1022  partly sunny      1            3        2         2
 212       1022  partly sunny      1            3        2         1
 213       1022  partly sunny      1            3        2         2
 214       1022  partly sunny      1            3        2         3
 215       1022  partly sunny      1            3        2         1

      Arrival_I    WI    LI  ddd ...   I_SC                  SD  \
 210          1  1800  75.0    1 ...      0 2018-01-31 11:36:00
 211          0   500  30.0    1 ...      0 2018-01-31 12:04:00
 212          0   750  30.0    1 ...      0 2018-01-31 12:39:00
 213          1   500  30.0    1 ...      0 2018-01-31 13:34:00
 214          0   200   NaN    1 ...      0 2018-01-31 13:54:00
 215          0   750  30.0    1 ...      0 2018-01-31 14:49:00

                      ED  LCAW  SQuery  CWP   TW G_P G_S  G_V
 210 2018-01-31 11:36:00   6.0     2.0  4.0  1.0   4   3    4
 211 2018-01-31 12:04:00   4.0     3.0  2.0  3.0   4   3    4
 212 2018-01-31 12:40:00   4.0     1.0  3.0  1.0   4   3    4
 213 2018-01-31 13:34:00   3.0     1.0  2.0  1.0   4   3    4
 214 2018-01-31 13:54:00   2.0     1.0  3.0  1.0   4   3    4
 215 2018-01-31 14:50:00   4.0     3.0  3.0  1.0   4   3    4

 [6 rows x 26 columns],
      Office_ID       Weather  Setup  Occupant_ID  Cluster  Distance  \
 140       1034  partly sunny      1            4        2         1
 141       1034  partly sunny      1            4        2         3
 142       1034  partly sunny      1            4        2         2
 143       1034  partly sunny      1            4        2         3
 144       1034  partly sunny      1            4        2         1
 145       1034  partly sunny      1            4        2         2

      Arrival_I    WI     LI  ddd ...   I_SC                  SD  \
 140          1  1100   35.0    1 ...      0 2017-12-16 11:32:13
 141          0   200    NaN    1 ...      0 2017-12-16 11:56:48
 142          0   500  100.0    1 ...      0 2017-12-16 12:23:18
 143          1   200    NaN    1 ...      0 2017-12-16 14:34:53
 144          0   750   40.0    1 ...      0 2017-12-16 14:57:59
 145          0   500  100.0    1 ...      0 2017-12-16 15:25:05

                      ED  LCAW  SQuery  CWP   TW G_P G_S  G_V
 140 2017-12-16 11:33:10   6.0     3.0  5.0  3.0   4   2    3
 141 2017-12-16 11:57:53   3.0     1.0  3.0  1.0   4   2    3
 142 2017-12-16 12:24:10   6.0     3.0  4.0  3.0   4   2    3
 143 2017-12-16 14:35:25   2.0     1.0  2.0  3.0   4   2    3
 144 2017-12-16 14:58:30   6.0     3.0  5.0  3.0   4   2    3
 145 2017-12-16 15:25:32   6.0     3.0  4.0  1.0   4   2    3

 [6 rows x 26 columns],
      Office_ID Weather  Setup  Occupant_ID  Cluster  Distance  Arrival_I  \
 120       1034   sunny      1            5        2         1          1
 121       1034   sunny      1            5        2         3          0
 122       1034   sunny      1            5        2         2          0
 123       1034   sunny      1            5        2         3          1
 124       1034   sunny      1            5        2         1          0
 125       1034   sunny      1            5        2         2          0

        WI     LI  ddd ...   I_SC                  SD                  ED  \
 120  1100   35.0    1 ...      0 2017-12-08 11:32:13 2017-12-08 11:33:10
 121   200    NaN    1 ...      0 2017-12-08 11:56:48 2017-12-08 11:57:53
 122   500  100.0    1 ...      0 2017-12-08 12:23:18 2017-12-08 12:24:10
 123   200    NaN    1 ...      0 2017-12-08 14:34:53 2017-12-08 14:35:25
 124   750   40.0    1 ...      0 2017-12-08 14:57:59 2017-12-08 14:58:30
 125   500  100.0    1 ...      0 2017-12-08 15:25:05 2017-12-08 15:25:32

      LCAW  SQuery  CWP   TW G_P G_S  G_V
 120   6.0     3.0  5.0  3.0   5   3    2
 121   3.0     1.0  3.0  1.0   5   3    2
 122   6.0     3.0  4.0  3.0   5   3    2
 123   2.0     1.0  2.0  3.0   5   3    2
 124   6.0     3.0  5.0  3.0   5   3    2
 125   6.0     3.0  4.0  1.0   5   3    2

 [6 rows x 26 columns],
      Office_ID       Weather  Setup  Occupant_ID  Cluster  Distance  \
 240       1034  partly sunny      1            6        2         3
 241       1034  partly sunny      1            6        2         2
 242       1034  partly sunny      1            6        2         1
 243       1034  partly sunny      1            6        2         2
 244       1034  partly sunny      1            6        2         3
 245       1034  partly sunny      1            6        2         1

      Arrival_I    WI    LI  ddd ...   I_SC                  SD  \
 240          1  1800  75.0    1 ...      0 2018-01-31 11:36:44
 241          0   500  30.0    1 ...      0 2018-01-31 12:04:23
 242          0   750  30.0    1 ...      0 2018-01-31 12:40:11
 243          1   500  30.0    1 ...      0 2018-01-31 13:34:43
 244          0   200   NaN    1 ...      0 2018-01-31 13:54:32
 245          0   750  30.0    1 ...      0 2018-01-31 14:50:13

                      ED  LCAW  SQuery  CWP   TW G_P G_S  G_V
 240 2018-01-31 11:36:55   6.0     1.0  3.0  3.0   4   2    3
 241 2018-01-31 12:04:34   3.0     1.0  4.0  1.0   4   2    3
 242 2018-01-31 12:40:23   4.0     3.0  4.0  1.0   4   2    3
 243 2018-01-31 13:34:59   4.0     1.0  3.0  1.0   4   2    3
 244 2018-01-31 13:54:44   3.0     1.0  4.0  1.0   4   2    3
 245 2018-01-31 14:50:23   4.0     3.0  3.0  1.0   4   2    3

 [6 rows x 26 columns],
      Office_ID           Weather  Setup  Occupant_ID  Cluster  Distance  \
 192       1020  completely sunny      1            7        3         3
 193       1020  completely sunny      1            7        3         1
 194       1020  completely sunny      1            7        3         2
 195       1020  completely sunny      1            7        3         2
 196       1020  completely sunny      1            7        3         1
 197       1020  completely sunny      1            7        3         3

      Arrival_I    WI     LI  ddd ...   I_SC                  SD  \
 192          1  1500  100.0    1 ...      0 2018-02-02 11:36:54
 193          0   300    NaN    1 ...      0 2018-02-02 11:59:15
 194          0   800  100.0    1 ...      0 2018-02-02 12:22:58
 195          1   800  100.0    1 ...      0 2018-02-02 12:42:18
 196          0   300    NaN    1 ...      0 2018-02-02 13:28:50
 197          0  1500  100.0    1 ...      0 2018-02-02 14:06:54

                      ED  LCAW  SQuery  CWP   TW G_P G_S  G_V
 192 2018-02-02 11:37:05   6.0     2.0  4.0  1.0   2   4    1
 193 2018-02-02 11:59:26   4.0     3.0  3.0  1.0   2   4    1
 194 2018-02-02 12:24:03   7.0     2.0  4.0  1.0   2   4    1
 195 2018-02-02 12:42:29   6.0     2.0  3.0  1.0   2   4    1
 196 2018-02-02 13:29:01   3.0     3.0  4.0  1.0   2   4    1
 197 2018-02-02 14:07:05   6.0     2.0  4.0  1.0   2   4    1

 [6 rows x 26 columns],
      Office_ID Weather  Setup  Occupant_ID  Cluster  Distance  Arrival_I  \
 126       1034  cloudy      1            8        3         1          1
 127       1034  cloudy      1            8        3         3          0
 128       1034  cloudy      1            8        3         2          0
 129       1034  cloudy      1            8        3         1          1
 130       1034  cloudy      1            8        3         2          0
 131       1034  cloudy      1            8        3         3          0

        WI     LI  ddd ...   I_SC                  SD                  ED  \
 126   300    NaN    1 ...      0 2017-12-09 11:18:40 2017-12-09 11:18:52
 127  2000  100.0    1 ...      0 2017-12-09 11:47:54 2017-12-09 11:48:06
 128   700   25.0    1 ...      0 2017-12-09 12:12:38 2017-12-09 12:12:47
 129   300    NaN    1 ...      0 2017-12-09 12:52:36 2017-12-09 12:52:47
 130   700   25.0    1 ...      0 2017-12-09 13:44:08 2017-12-09 13:44:17
 131  2000  100.0    1 ...      0 2017-12-09 14:13:08 2017-12-09 14:13:19

      LCAW  SQuery  CWP   TW G_P G_S  G_V
 126   3.0     3.0  4.0  3.0   2   5    1
 127   7.0     2.0  2.0  1.0   2   5    1
 128   6.0     2.0  2.0  1.0   2   5    1
 129   3.0     3.0  5.0  1.0   2   5    1
 130   5.0     2.0  2.0  1.0   2   5    1
 131   7.0     2.0  1.0  1.0   2   5    1

 [6 rows x 26 columns],
      Office_ID       Weather  Setup  Occupant_ID  Cluster  Distance  \
 164       1034  partly sunny      1            9        3         3
 165       1034  partly sunny      1            9        3         2
 166       1034  partly sunny      1            9        3         1
 167       1034  partly sunny      1            9        3         2
 168       1034  partly sunny      1            9        3         3
 169       1034  partly sunny      1            9        3         1

      Arrival_I    WI     LI  ddd ...   I_SC                  SD  \
 164          1  1500  100.0    0 ...      0                 NaT
 165          0   800  100.0    1 ...      0 2018-01-26 11:18:22
 166          0   300    NaN    1 ...      0 2018-01-26 12:06:06
 167          1   800  100.0    1 ...      0 2018-01-26 12:42:38
 168          0  1500  100.0    1 ...      0 2018-01-26 13:27:37
 169          0   300    NaN    1 ...      0 2018-01-26 13:51:58

                      ED  LCAW  SQuery  CWP   TW G_P G_S  G_V
 164                 NaT   NaN     NaN  NaN  NaN   2   4    3
 165 2018-01-26 11:18:50   7.0     2.0  1.0  1.0   2   4    3
 166 2018-01-26 12:06:19   4.0     1.0  3.0  1.0   2   4    3
 167 2018-01-26 12:42:52   6.0     2.0  3.0  1.0   2   4    3
 168 2018-01-26 13:27:54   7.0     2.0  1.0  1.0   2   4    3
 169 2018-01-26 13:52:12   3.0     3.0  1.0  1.0   2   4    3

 [6 rows x 26 columns],
      Office_ID Weather  Setup  Occupant_ID  Cluster  Distance  Arrival_I  \
 132       1034  cloudy      1           10        3         2          1
 133       1034  cloudy      1           10        3         1          0
 134       1034  cloudy      1           10        3         3          0
 135       1034  cloudy      1           10        3         1          1
 136       1034  cloudy      1           10        3         2          0
 137       1034  cloudy      1           10        3         3          0

        WI     LI  ddd ...   I_SC                  SD                  ED  \
 132   700   25.0    1 ...      0 2017-12-11 10:53:16 2017-12-11 10:53:35
 133   300    NaN    1 ...      0 2017-12-11 11:16:13 2017-12-11 11:16:24
 134  2000  100.0    1 ...      0 2017-12-11 11:50:12 2017-12-11 11:50:21
 135   300    NaN    1 ...      0 2017-12-11 12:15:20 2017-12-11 12:15:39
 136   700   25.0    1 ...      0 2017-12-11 14:19:09 2017-12-11 14:19:21
 137  2000  100.0    1 ...      0 2017-12-11 14:38:30 2017-12-11 14:38:43

      LCAW  SQuery  CWP   TW G_P G_S  G_V
 132   5.0     2.0  3.0  1.0   4   4    2
 133   3.0     3.0  3.0  1.0   4   4    2
 134   6.0     2.0  2.0  1.0   4   4    2
 135   3.0     3.0  3.0  1.0   4   4    2
 136   5.0     2.0  2.0  1.0   4   4    2
 137   4.0     3.0  2.0  3.0   4   4    2

 [6 rows x 26 columns],
      Office_ID Weather  Setup  Occupant_ID  Cluster  Distance  Arrival_I   WI  \
 138       1034  cloudy      1           11        1         2          1  700
 139       1034  cloudy      1           11        1         2          0  700

        LI  ddd ...   I_SC                  SD                  ED  LCAW  \
 138  25.0    1 ...      0 2017-12-13 11:42:58 2017-12-13 11:43:09   3.0
 139  25.0    1 ...      0 2017-12-13 13:02:28 2017-12-13 13:02:39   2.0

      SQuery  CWP   TW G_P G_S  G_V
 138     1.0  3.0  1.0   6   3    4
 139     1.0  2.0  3.0   6   3    4

 [2 rows x 26 columns],
      Office_ID            Weather  Setup  Occupant_ID  Cluster  Distance  \
 186       1020  completely cloudy      1           12        1         3
 187       1020  completely cloudy      1           12        1         2
 188       1020  completely cloudy      1           12        1         1
 189       1020  completely cloudy      1           12        1         2
 190       1020  completely cloudy      1           12        1         1
 191       1020  completely cloudy      1           12        1         3

      Arrival_I    WI     LI  ddd ...   I_SC                  SD  \
 186          1   300    NaN    1 ...      0 2018-02-01 11:33:15
 187          0   500   25.0    1 ...      0 2018-02-01 11:59:21
 188          0  1100  100.0    1 ...      0 2018-02-01 12:27:05
 189          1   500   25.0    1 ...      0 2018-02-01 13:07:21
 190          0  1100  100.0    1 ...      0 2018-02-01 13:42:03
 191          0   300    NaN    1 ...      0 2018-02-01 14:12:08

                      ED  LCAW  SQuery  CWP   TW G_P G_S  G_V
 186 2018-02-01 11:33:35   2.0     1.0  4.0  1.0   5   2    5
 187 2018-02-01 11:59:51   3.0     1.0  3.0  1.0   5   2    5
 188 2018-02-01 12:27:19   6.0     3.0  5.0  1.0   5   2    5
 189 2018-02-01 13:07:42   3.0     3.0  3.0  1.0   5   2    5
 190 2018-02-01 13:42:16   4.0     1.0  3.0  1.0   5   2    5
 191 2018-02-01 14:12:17   2.0     1.0  1.0  3.0   5   2    5

 [6 rows x 26 columns],
      Office_ID       Weather  Setup  Occupant_ID  Cluster  Distance  \
 180       1020  partly sunny      1           13        1         3
 181       1020  partly sunny      1           13        1         2
 182       1020  partly sunny      1           13        1         1
 183       1020  partly sunny      1           13        1         2
 184       1020  partly sunny      1           13        1         3
 185       1020  partly sunny      1           13        1         1

      Arrival_I    WI     LI  ddd ...   I_SC                  SD  \
 180          1   300    NaN    1 ...      0 2018-01-31 11:35:49
 181          0   700   50.0    1 ...      0 2018-01-31 12:03:33
 182          0  1100  100.0    1 ...      0 2018-01-31 12:39:22
 183          1   700   50.0    1 ...      0 2018-01-31 13:33:49
 184          0   300    NaN    1 ...      0 2018-01-31 13:53:47
 185          0  1100  100.0    1 ...      0 2018-01-31 14:49:25

                      ED  LCAW  SQuery  CWP   TW G_P G_S  G_V
 180 2018-01-31 11:36:01   2.0     1.0  2.0  1.0   6   3    5
 181 2018-01-31 12:03:45   4.0     3.0  3.0  1.0   6   3    5
 182 2018-01-31 12:39:34   5.0     3.0  2.0  3.0   6   3    5
 183 2018-01-31 13:34:03   4.0     1.0  5.0  1.0   6   3    5
 184 2018-01-31 13:53:58   2.0     1.0  3.0  1.0   6   3    5
 185 2018-01-31 14:49:35   5.0     3.0  4.0  1.0   6   3    5

 [6 rows x 26 columns],
      Office_ID Weather  Setup  Occupant_ID  Cluster  Distance  Arrival_I  \
 146       1020   sunny      1           14        1         1          1
 147       1020   sunny      1           14        1         2          0
 148       1020   sunny      1           14        1         3          0
 149       1020   sunny      1           14        1         3          1
 150       1020   sunny      1           14        1         1          0
 151       1020   sunny      1           14        1         2          0

        WI     LI  ddd ...   I_SC                  SD                  ED  \
 146  1100  100.0    1 ...      0 2017-12-19 11:47:27 2017-12-19 11:48:09
 147   700   25.0    1 ...      0 2017-12-19 12:08:40 2017-12-19 12:09:19
 148   300    NaN    1 ...      0 2017-12-19 12:42:58 2017-12-19 12:43:29
 149   300    NaN    1 ...      0 2017-12-19 13:01:33 2017-12-19 13:02:08
 150  1100  100.0    1 ...      0 2017-12-19 13:22:57 2017-12-19 13:23:17
 151   700   25.0    1 ...      0 2017-12-19 13:58:32 2017-12-19 13:58:46

      LCAW  SQuery  CWP   TW G_P G_S  G_V
 146   6.0     1.0  5.0  3.0   5   2    5
 147   5.0     1.0  5.0  2.0   5   2    5
 148   3.0     1.0  4.0  1.0   5   2    5
 149   6.0     3.0  5.0  3.0   5   2    5
 150   6.0     3.0  4.0  1.0   5   2    5
 151   4.0     1.0  3.0  1.0   5   2    5

 [6 rows x 26 columns],
      Office_ID Weather  Setup  Occupant_ID  Cluster  Distance  Arrival_I  \
 152       1034   sunny      1           15        1         3          1
 153       1034   sunny      1           15        1         2          0
 154       1034   sunny      1           15        1         1          0
 155       1034   sunny      1           15        1         1          1
 156       1034   sunny      1           15        1         3          0
 157       1034   sunny      1           15        1         2          0

        WI     LI  ddd ...   I_SC                  SD                  ED  \
 152   300    NaN    1 ...      0 2017-12-19 11:48:47 2017-12-19 11:49:24
 153   700   25.0    1 ...      0 2017-12-19 12:08:41 2017-12-19 12:08:49
 154  1100  100.0    1 ...      0 2017-12-19 12:43:29 2017-12-19 12:43:45
 155  1100  100.0    1 ...      0 2017-12-19 13:00:53 2017-12-19 13:01:05
 156   300    NaN    1 ...      0 2017-12-19 13:23:19 2017-12-19 13:23:29
 157   700   25.0    1 ...      0 2017-12-19 13:57:31 2017-12-19 13:57:41

      LCAW  SQuery  CWP   TW G_P G_S  G_V
 152   3.0     3.0  3.0  1.0   6   3    3
 153   3.0     1.0  3.0  1.0   6   3    3
 154   6.0     3.0  4.0  3.0   6   3    3
 155   4.0     1.0  2.0  1.0   6   3    3
 156   2.0     1.0  3.0  1.0   6   3    3

In [7]:
for i,s in enumerate(Setup1):
    print 'Occupant:' + str(i+1)
    print 'Cluster:' + str(s.Cluster.unique())
    print s.WI.unique()
    print '.'*40

Occupant:1
       WI  SQuery
158   300     3.0
159   700     3.0
160  2000     2.0
161   300     3.0
162  2000     2.0
163   700     2.0
Occupant:2
       WI  SQuery
114   300     NaN
115   700     2.0
116  2000     2.0
117   300     3.0
118  2000     2.0
119   700     2.0
Occupant:3
       WI  SQuery
210  1800     2.0
211   500     3.0
212   750     1.0
213   500     1.0
214   200     1.0
215   750     3.0
Occupant:4
       WI  SQuery
140  1100     3.0
141   200     1.0
142   500     3.0
143   200     1.0
144   750     3.0
145   500     3.0
Occupant:5
       WI  SQuery
120  1100     3.0
121   200     1.0
122   500     3.0
123   200     1.0
124   750     3.0
125   500     3.0
Occupant:6
       WI  SQuery
240  1800     1.0
241   500     1.0
242   750     3.0
243   500     1.0
244   200     1.0
245   750     3.0
Occupant:7
       WI  SQuery
192  1500     2.0
193   300     3.0
194   800     2.0
195   800     2.0
196   300     3.0
197  1500     2.0
Occupant:8
       WI  SQuery
126   300     3.0
127  2000     2.0
128   700     2.0
129   300     3.0
130   700     2.0
131  2000     2.0
Occupant:9
       WI  SQuery
164  1500     NaN
165   800     2.0
166   300     1.0
167   800     2.0
168  1500     2.0
169   300     3.0
Occupant:10
       WI  SQuery
132   700     2.0
133   300     3.0
134  2000     2.0
135   300     3.0
136   700     2.0
137  2000     3.0
Occupant:11
      WI  SQuery
138  700     1.0
139  700     1.0
Occupant:12
       WI  SQuery
186   300     1.0
187   500     1.0
188  1100     3.0
189   500     3.0
190  1100     1.0
191   300     1.0
Occupant:13
       WI  SQuery
180   300     1.0
181   700     3.0
182  1100     3.0
183   700     1.0
184   300     1.0
185  1100     3.0
Occupant:14
       WI  SQuery
146  1100     1.0
147   700     1.0
148   300     1.0
149   300     3.0
150  1100     3.0
151   700     1.0
Occupant:15
       WI  SQuery
152   300     3.0
153   700     1.0
154  1100     3.0
155  1100     1.0
156   300     1.0
157   700     3.0
Occupant:16
       WI  SQuery
378   300     1.0
379   500     1.0
380  1100     3.0
381  1100     3.0
382   500     3.0
383   300     3.0
Occupant:17
       WI  SQuery
402   300     3.0
403  1500     2.0
404   800     3.0
405  1500     2.0
406   800     2.0
407   300     3.0
Occupant:18
Empty DataFrame
Columns: [WI, SQuery]
Index: []
Occupant:19
       WI  SQuery
408   700     3.0
409  1100     3.0
410   300     1.0
411  1100     3.0
412   700     3.0
413   300     3.0

In [9]:
for i,s in enumerate(Setup1):
    print 'Occupant:' + str(i+1)
    print 'Cluster:' + str(s.Cluster.unique())
    print s.WI.unique()
    print '.'*40

Occupant:1
Cluster:[3]
[ 300  700 2000]
........................................
Occupant:2
Cluster:[3]
[ 300  700 2000]
........................................
Occupant:3
Cluster:[2]
[1800  500  750  200]
........................................
Occupant:4
Cluster:[2]
[1100  200  500  750]
........................................
Occupant:5
Cluster:[2]
[1100  200  500  750]
........................................
Occupant:6
Cluster:[2]
[1800  500  750  200]
........................................
Occupant:7
Cluster:[3]
[1500  300  800]
........................................
Occupant:8
Cluster:[3]
[ 300 2000  700]
........................................
Occupant:9
Cluster:[3]
[1500  800  300]
........................................
Occupant:10
Cluster:[3]
[ 700  300 2000]
........................................
Occupant:11
Cluster:[1]
[700]
........................................
Occupant:12
Cluster:[1]
[ 300  500 1100]
........................................
Occupant:13
Cluster:[1]
[ 300  700 1100]
........................................
Occupant:14
Cluster:[1]
[1100  700  300]
........................................
Occupant:15
Cluster:[1]
[ 300  700 1100]
........................................
Occupant:16
Cluster:[1]
[ 300  500 1100]
........................................
Occupant:17
Cluster:[3]
[ 300 1500  800]
........................................
Occupant:18
Cluster:[]
[]
........................................
Occupant:19
Cluster:[1]
[ 700 1100  300]
........................................

In [8]:
for i,s in enumerate(Setup2):
    print 'Occupant:' + str(i+1)
    print 'Cluster:' + str(s.Cluster.unique())
    print s.WI.unique()
    print '.'*40

Occupant:1
Cluster:[3]
[ 300  700 2000  800 1500]
........................................
Occupant:2
Cluster:[3]
[ 300  800 1500]
........................................
Occupant:3
Cluster:[2]
[1100 1800  500  750  200]
........................................
Occupant:4
Cluster:[2]
[1100 1800  500  750  200]
........................................
Occupant:5
Cluster:[2]
[1800  750  500]
........................................
Occupant:6
Cluster:[2]
[1700  500 1100  200 1800  750]
........................................
Occupant:7
Cluster:[3]
[ 700  300 2000 1500  800]
........................................
Occupant:8
Cluster:[3]
[1500  800  300  700 2000]
........................................
Occupant:9
Cluster:[3]
[ 700  300 2000 1500  800]
........................................
Occupant:10
Cluster:[3]
[ 300 2000  700 1500  800]
........................................
Occupant:11
Cluster:[1]
[ 700  300 1100  500]
........................................
Occupant:12
Cluster:[1]
[ 700  300 1100]
........................................
Occupant:13
Cluster:[1]
[ 300 1100  700]
........................................
Occupant:14
Cluster:[1]
[ 700  300 1100]
........................................
Occupant:15
Cluster:[1]
[ 300 1100  700]
........................................
Occupant:16
Cluster:[1]
[1100  300  500  700]
........................................
Occupant:17
Cluster:[3]
[ 300 1500  800  700 2000]
........................................
Occupant:18
Cluster:[1]
[ 300 1100  500]
........................................
Occupant:19
Cluster:[]
[]
........................................